version: '3'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env

  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: always

  app:
    image: nextcloud:24-fpm-alpine
    container_name: nextcloud
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    image: nginx:1.21-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - nextcloud:/var/www/html:ro
      - ./nginx.conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - acme:/opt/www/acme
    depends_on:
      - app

volumes:
  db:
  nextcloud:
  acme:
