---
# handlers file for ansible/roles/nginx_install
- name: start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
    enabled: yes